server:
    port: 8090

management:
    server:
        port: 8091
    endpoints:
        web:
            base-path: /manager
            exposure:
                include: "*"
    trace:
        http:
            enabled: true
    info:
        env:
            enabled: true
            show-values: always
        os:
            enabled: true
        java:
            enabled: true
#                exclude: "env, beans"

#works
#logging:
#   file:
#       name: "C:/Users/Shumin/projects/spring-boot-tutorial/logs/my-spring.log"

spring:
    profiles:
        active: dev
---
spring:
    config:
        activate:
            on-profile: dev
#Works
#        import:
#            - ./dev/swager-openapi.properties
#            - ./dev/logger-dev.properties

#For default Spring-offered access authentication
    security:
        user:
            password: user

#For OAuth2
        oauth2:
            client:
                registration:
                    github:
#Also works
#                       client-id: Iv23ctgAMjS3v0ZAYMf5
#                       client-secret: 156db1a6100e31a086fee459d7f45f3830543e43
                        clientId: Iv23ctgAMjS3v0ZAYMf5
                        clientSecret: f4b5e07831229507aa187bec075b7b18bf938583

        application:
        name: spring-boot-tutorial
    datasource:
        url: jdbc:mysql://localhost:3306/dcbapp
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: admin123
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    app:
        jwtSecret:  mySecretKey123456789fewq34qhgqhfqphfqhfqhqphfqhferqrqwfeqfwqi93yrfhqhfqqvalai988349pqqhvoifp98hwphpwqvpqvpqvpqvqvknfqfn9wrrf
        jwtExpirationMs: 36000000

#Works
#logging:
#  file:
#    name: "C:/Users/Shumin/projects/spring-boot-tutorial/logs/my-spring-boot.log"

#Works
#protocol:
#    type: http
#    port: 8090
---

spring:
    config:
        activate:
            on-profile: test

    application:
        name: spring-boot-tutorial
    datasource:
        url: jdbc:mysql://localhost:3306/dcbapp-test
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: admin123
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
---

spring:
    config:
        activate:
            on-profile: prod

    application:
        name: spring-boot-tutorial
    datasource:
        url: jdbc:mysql://localhost:3306/dcbapp-prod
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: admin123
    jpa:
        hibernate:
            ddl-auto: update
    show-sql: true

---
welcome:
    message: Welcome to Spring Boot!
