server:
    port: 8060

management:
    server:
        port: 8070
    endpoints:
        web:
            base-path: /manager
            exposure:
                include: "*"
    trace:
        http:
            enabled: true
    info:
        env:
            enabled: true
            show-values: always
        os:
            enabled: true
        java:
            enabled: true
#                exclude: "env, beans"

#works
#logging:
#   file:
#       name: "C:/Users/Shumin/projects/spring-boot-tutorial/logs/my-spring.log"

spring:
    profiles:
        active: dev
---
spring:
    application:
        name: spring-boot-tutorial

    config:
        activate:
            on-profile: dev
#Works
#        import:
#            - ./dev/swager-openapi.properties
#            - ./dev/logger-dev.properties

#For default Spring-offered access authentication
    security:
        user:
            name: user
            password: user



    datasource:
        url: jdbc:mysql://localhost:3306/dcbapp
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: admin123
    jpa:
        hibernate:
#            Modification of schema may happen due to any JPA changes but tables or columns even if they are no more required by the application
            ddl-auto: update
        show-sql: true

#In-memoery-DB based DataSource
#    h2:
#      console:
#          enabled: true
#    datasource:
#        url: jdbc:h2:mem:test

    app:
        jwtSecret:  mySecretKey123456789fewq34qhgqhfqphfqhfqhqphfqhferqrqwfeqfwqi93yrfhqhfqqvalai988349pqqhvoifp98hwphpwqvpqvpqvpqvqvknfqfn9wrrf
        jwtExpirationMs: 36000000

#Works
#logging:
#  file:
#    name: "C:/Users/Shumin/projects/spring-boot-tutorial/logs/my-spring-boot.log"

#Works
#protocol:
#    type: http
#    port: 8090
---

spring:
    application:
        name: spring-boot-tutorial-on-test

    config:
        activate:
            on-profile: test


    datasource:
        url: jdbc:mysql://localhost:3306/dcbapp-test
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: admin123
    jpa:
        hibernate:
#            similar to create, with the addition that Hibernate will drop the database after all operations are completed. Typically used for unit testing
            ddl-auto: create-drop
        show-sql: true
---

spring:
    config:
        activate:
            on-profile: prod

    application:
        name: spring-boot-tutorial-on-prod
    datasource:
        url: jdbc:mysql://localhost:3306/dcbapp-prod
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: admin123
    jpa:
        hibernate:
#            Hibernate only validates whether the tables and columns exist. update/create is typically not used directly in PROD to avoid unwanted create-drop/update of schema
#            ddl-auto: validate
            ddl-auto: none
    show-sql: true

---
welcome:
    message: Welcome to Spring Boot!
